# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ItemSellBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, item_id: float=None, quantity: float=None):  # noqa: E501
        """ItemSellBody - a model defined in Swagger

        :param item_id: The item_id of this ItemSellBody.  # noqa: E501
        :type item_id: float
        :param quantity: The quantity of this ItemSellBody.  # noqa: E501
        :type quantity: float
        """
        self.swagger_types = {
            'item_id': float,
            'quantity': float
        }

        self.attribute_map = {
            'item_id': 'ItemID',
            'quantity': 'Quantity'
        }
        self._item_id = item_id
        self._quantity = quantity

    @classmethod
    def from_dict(cls, dikt) -> 'ItemSellBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The item_sell_body of this ItemSellBody.  # noqa: E501
        :rtype: ItemSellBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def item_id(self) -> float:
        """Gets the item_id of this ItemSellBody.


        :return: The item_id of this ItemSellBody.
        :rtype: float
        """
        return self._item_id

    @item_id.setter
    def item_id(self, item_id: float):
        """Sets the item_id of this ItemSellBody.


        :param item_id: The item_id of this ItemSellBody.
        :type item_id: float
        """

        self._item_id = item_id

    @property
    def quantity(self) -> float:
        """Gets the quantity of this ItemSellBody.


        :return: The quantity of this ItemSellBody.
        :rtype: float
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity: float):
        """Sets the quantity of this ItemSellBody.


        :param quantity: The quantity of this ItemSellBody.
        :type quantity: float
        """

        self._quantity = quantity
