# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class ItemType(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, price: float=None):  # noqa: E501
        """ItemType - a model defined in Swagger

        :param name: The name of this ItemType.  # noqa: E501
        :type name: str
        :param price: The price of this ItemType.  # noqa: E501
        :type price: float
        """
        self.swagger_types = {
            'name': str,
            'price': float
        }

        self.attribute_map = {
            'name': 'name',
            'price': 'price'
        }
        self._name = name
        self._price = price

    @classmethod
    def from_dict(cls, dikt) -> 'ItemType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ItemType of this ItemType.  # noqa: E501
        :rtype: ItemType
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this ItemType.


        :return: The name of this ItemType.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this ItemType.


        :param name: The name of this ItemType.
        :type name: str
        """

        self._name = name

    @property
    def price(self) -> float:
        """Gets the price of this ItemType.


        :return: The price of this ItemType.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price: float):
        """Sets the price of this ItemType.


        :param price: The price of this ItemType.
        :type price: float
        """

        self._price = price
