# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Store(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, maxstore: float=None):  # noqa: E501
        """Store - a model defined in Swagger

        :param name: The name of this Store.  # noqa: E501
        :type name: str
        :param maxstore: The maxstore of this Store.  # noqa: E501
        :type maxstore: float
        """
        self.swagger_types = {
            'name': str,
            'maxstore': float
        }

        self.attribute_map = {
            'name': 'name',
            'maxstore': 'maxstore'
        }
        self._name = name
        self._maxstore = maxstore

    @classmethod
    def from_dict(cls, dikt) -> 'Store':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Store of this Store.  # noqa: E501
        :rtype: Store
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this Store.


        :return: The name of this Store.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Store.


        :param name: The name of this Store.
        :type name: str
        """

        self._name = name

    @property
    def maxstore(self) -> float:
        """Gets the maxstore of this Store.


        :return: The maxstore of this Store.
        :rtype: float
        """
        return self._maxstore

    @maxstore.setter
    def maxstore(self, maxstore: float):
        """Sets the maxstore of this Store.


        :param maxstore: The maxstore of this Store.
        :type maxstore: float
        """

        self._maxstore = maxstore
